### PR TITLE
Retry connection establishment, defaulting to 3 tries

### PR DESCRIPTION
**Pull request by djc**
This fixes the test from #45. @bbigras, would you like to review? You managed to find the one `TODO` in the library. @khuey, if you have some time to spare, review would be much appreciated too. I'd like to get this merged and then put out a first release soon after.

### CODE REVIEW

**Comment by djc** [comment]
For easiest review, [ignore the whitespace changes](https://github.com/khuey/bb8/pull/51/commits/fa98aabb88ba47221c6fef94ea4e164294a2313c?w=1).

**Comment by djc** [comment]
Points of potential discussion:

* Bikeshedding the configuration item name
* Is the negative test useful here?

**Comment by djc** [comment]
I changed this to not rely on a number of retries and instead copy the exponential backoff strategy from r2d2. However, for now it will terminate after `connection_timeout`. I think this is a pretty good solution for now and will merge this, happy to get any feedback post-merge.

**Comment by bbigras** [comment]
Thanks for the work @djc . Sorry I didn't reply last time. I have been busy and lazy during the holidays.

**Comment by djc** [comment]
@bbigras, no problem, that's what holidays are for!

**Pull request merged**
